/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JMediGLFrame.java
 *
 * Created on 13.06.2010, 18:44:43
 */
package org.yourorghere;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.dicom4j.dicom.DicomException;
import org.dicom4j.images.DicomFrame;
import org.dicom4j.images.DicomImage;
import org.dicom4j.images.DicomImageReader;
import org.dicom4j.images.DicomImageReaderException;
import org.dicom4j.io.media.DicomFile;

/**
 *
 * @author uli
 */
public class JMediGLFrame extends javax.swing.JFrame {

    /** Creates new form JMediGLFrame */
    public JMediGLFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gLJPanel1 = new javax.media.opengl.GLJPanel();
        ilabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openSingleDicomMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout gLJPanel1Layout = new javax.swing.GroupLayout(gLJPanel1);
        gLJPanel1.setLayout(gLJPanel1Layout);
        gLJPanel1Layout.setHorizontalGroup(
            gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        gLJPanel1Layout.setVerticalGroup(
            gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        openSingleDicomMenuItem.setText("Open DICOM file");
        openSingleDicomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSingleDicomMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openSingleDicomMenuItem);

        menuBar.add(fileMenu);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gLJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gLJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openSingleDicomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSingleDicomMenuItemActionPerformed
        openSingleDICOMFile();
    }//GEN-LAST:event_openSingleDicomMenuItemActionPerformed

    private void openSingleDICOMFile() {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File selectedFile = fc.getSelectedFile();
        DicomFile df = new DicomFile(selectedFile);
        try {
            DicomImage r = DicomImageReader.createDicomFrames(df.getDataset());
            ilabel.setIcon(new ImageIcon(r.getFrame(0)));
        } catch (DicomImageReaderException ex) {
            Logger.getLogger(JMediGLFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DicomException ex) {
            Logger.getLogger(JMediGLFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JMediGLFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.media.opengl.GLJPanel gLJPanel1;
    private javax.swing.JLabel ilabel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openSingleDicomMenuItem;
    // End of variables declaration//GEN-END:variables
}
